### ISSUE TITLE
Build failure with errors related to standard integer types (uint*_t) in tiff function signatures.

### ISSUE THREAD

**Issue by ReubenBellika** [asgr/imager#16]
Recently I have had build failures for the current CRAN version of imager (0.45.8) in certain environments (e.g. Debian Buster with libtiff-dev installed).

The errors reported relate to usage of standard integer types in the tiff function signatures, such as:
`../inst/include/CImg.h:51701:57: error: ‘uint16_t’ does not name a type; did you mean ‘u_int16_t’?`

It looks to me that CImg.h references these types without including `<cstdint>` as it should.

I can work around this issue by removing libtiff-dev, but at the expense of TIFF support.

I've attached a full build log with all errors.
[imager_0-45-8_build_log_2024-03-13.txt](https://github.com/asgr/imager/files/14593376/imager_0-45-8_build_log_2024-03-13.txt)

**Comment by rtobar** [comment]
@ReubenBellika this has been already reported in https://github.com/asgr/imager/issues/12, and a fix is available in `master`, although not in CRAN yet. I'll close as a duplicate.

**Comment by ReubenBellika** [comment]
Okay, thank you. Any idea when this may reach CRAN?

**Comment by rtobar** [comment]
Working on that, no clear date yet.
