### ISSUE TITLE
Install error in R 4.3.3

### ISSUE THREAD

**Issue by Marc-Girondot** [asgr/imager#19]
System: Ubuntu 22.04.4 LTS (GNU/Linux 5.15.0-105-generic x86_64) - Uptodate
 FFTW version 3.3.10 is installed
imager 0.45.8 already installed

In R: 
> install.packages("imager")
gives an error (see below).

Have you a solution... I searched for but I found nothing.
Thanks
Marc

In R: 
> install.packages("imager")
Installation du package dans ‘/home/mgirond/R/x86_64-pc-linux-gnu-library/4.3’
(car ‘lib’ n'est pas spécifié)
essai de l'URL 'https://cloud.r-project.org/src/contrib/imager_1.0.1.tar.gz'
Content type 'application/x-gzip' length 4509699 bytes (4.3 MB)
==================================================
downloaded 4.3 MB

* installing *source* package ‘imager’ ...
** package ‘imager’ correctement décompressé et sommes MD5 vérifiées
** using staged installation
checking for pkg-config... /usr/bin/pkg-config
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ -std=gnu++17 accepts -g... yes
checking how to run the C++ preprocessor... g++ -std=gnu++17 -E
checking for X... libraries , headers 
checking for XOpenDisplay in -lX11... yes
X11 library found.
configure: Checking if FFTW3 library is available using pkg-config
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for FFTW... yes
FFTW3 found!
checking whether pkg-config knows about libtiff-4... yes
checking for configurable backends... checking whether --static is needed... no
checking for g++ -std=gnu++17 option to support OpenMP... -fopenmp
configure: creating ./config.status
config.status: creating src/Makevars
** libs
using C++ compiler: ‘g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0’
using C++11
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -Dcimg_use_fftw3 -I/usr/local/include -I/usr/include/x86_64-linux-gnu -Dcimg_use_tiff -I../inst/include -DCIMG_COMPILING -Dcimg_use_rng -Dcimg_use_r -Dcimg_use_fftw3_singlethread -Dcimg_verbosity=1 -Dcimg_date='""' -Dcimg_time='""' -I'/usr/local/lib/R/site-library/Rcpp/include'    -fopenmp -fpic  -g -O2 -ffile-prefix-map=/build/r-base-14Q6vq/r-base-4.3.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -Dcimg_use_fftw3 -I/usr/local/include -I/usr/include/x86_64-linux-gnu -Dcimg_use_tiff -I../inst/include -DCIMG_COMPILING -Dcimg_use_rng -Dcimg_use_r -Dcimg_use_fftw3_singlethread -Dcimg_verbosity=1 -Dcimg_date='""' -Dcimg_time='""' -I'/usr/local/lib/R/site-library/Rcpp/include'    -fopenmp -fpic  -g -O2 -ffile-prefix-map=/build/r-base-14Q6vq/r-base-4.3.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c colourspace.cpp -o colourspace.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -Dcimg_use_fftw3 -I/usr/local/include -I/usr/include/x86_64-linux-gnu -Dcimg_use_tiff -I../inst/include -DCIMG_COMPILING -Dcimg_use_rng -Dcimg_use_r -Dcimg_use_fftw3_singlethread -Dcimg_verbosity=1 -Dcimg_date='""' -Dcimg_time='""' -I'/usr/local/lib/R/site-library/Rcpp/include'    -fopenmp -fpic  -g -O2 -ffile-prefix-map=/build/r-base-14Q6vq/r-base-4.3.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c coordinates.cpp -o coordinates.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -Dcimg_use_fftw3 -I/usr/local/include -I/usr/include/x86_64-linux-gnu -Dcimg_use_tiff -I../inst/include -DCIMG_COMPILING -Dcimg_use_rng -Dcimg_use_r -Dcimg_use_fftw3_singlethread -Dcimg_verbosity=1 -Dcimg_date='""' -Dcimg_time='""' -I'/usr/local/lib/R/site-library/Rcpp/include'    -fopenmp -fpic  -g -O2 -ffile-prefix-map=/build/r-base-14Q6vq/r-base-4.3.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c display.cpp -o display.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -Dcimg_use_fftw3 -I/usr/local/include -I/usr/include/x86_64-linux-gnu -Dcimg_use_tiff -I../inst/include -DCIMG_COMPILING -Dcimg_use_rng -Dcimg_use_r -Dcimg_use_fftw3_singlethread -Dcimg_verbosity=1 -Dcimg_date='""' -Dcimg_time='""' -I'/usr/local/lib/R/site-library/Rcpp/include'    -fopenmp -fpic  -g -O2 -ffile-prefix-map=/build/r-base-14Q6vq/r-base-4.3.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c drawing.cpp -o drawing.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -Dcimg_use_fftw3 -I/usr/local/include -I/usr/include/x86_64-linux-gnu -Dcimg_use_tiff -I../inst/include -DCIMG_COMPILING -Dcimg_use_rng -Dcimg_use_r -Dcimg_use_fftw3_singlethread -Dcimg_verbosity=1 -Dcimg_date='""' -Dcimg_time='""' -I'/usr/local/lib/R/site-library/Rcpp/include'    -fopenmp -fpic  -g -O2 -ffile-prefix-map=/build/r-base-14Q6vq/r-base-4.3.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c filtering.cpp -o filtering.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -Dcimg_use_fftw3 -I/usr/local/include -I/usr/include/x86_64-linux-gnu -Dcimg_use_tiff -I../inst/include -DCIMG_COMPILING -Dcimg_use_rng -Dcimg_use_r -Dcimg_use_fftw3_singlethread -Dcimg_verbosity=1 -Dcimg_date='""' -Dcimg_time='""' -I'/usr/local/lib/R/site-library/Rcpp/include'    -fopenmp -fpic  -g -O2 -ffile-prefix-map=/build/r-base-14Q6vq/r-base-4.3.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c hough.cpp -o hough.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -Dcimg_use_fftw3 -I/usr/local/include -I/usr/include/x86_64-linux-gnu -Dcimg_use_tiff -I../inst/include -DCIMG_COMPILING -Dcimg_use_rng -Dcimg_use_r -Dcimg_use_fftw3_singlethread -Dcimg_verbosity=1 -Dcimg_date='""' -Dcimg_time='""' -I'/usr/local/lib/R/site-library/Rcpp/include'    -fopenmp -fpic  -g -O2 -ffile-prefix-map=/build/r-base-14Q6vq/r-base-4.3.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c imgraphs.cpp -o imgraphs.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -Dcimg_use_fftw3 -I/usr/local/include -I/usr/include/x86_64-linux-gnu -Dcimg_use_tiff -I../inst/include -DCIMG_COMPILING -Dcimg_use_rng -Dcimg_use_r -Dcimg_use_fftw3_singlethread -Dcimg_verbosity=1 -Dcimg_date='""' -Dcimg_time='""' -I'/usr/local/lib/R/site-library/Rcpp/include'    -fopenmp -fpic  -g -O2 -ffile-prefix-map=/build/r-base-14Q6vq/r-base-4.3.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c interact.cpp -o interact.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -Dcimg_use_fftw3 -I/usr/local/include -I/usr/include/x86_64-linux-gnu -Dcimg_use_tiff -I../inst/include -DCIMG_COMPILING -Dcimg_use_rng -Dcimg_use_r -Dcimg_use_fftw3_singlethread -Dcimg_verbosity=1 -Dcimg_date='""' -Dcimg_time='""' -I'/usr/local/lib/R/site-library/Rcpp/include'    -fopenmp -fpic  -g -O2 -ffile-prefix-map=/build/r-base-14Q6vq/r-base-4.3.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c interpolation.cpp -o interpolation.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -Dcimg_use_fftw3 -I/usr/local/include -I/usr/include/x86_64-linux-gnu -Dcimg_use_tiff -I../inst/include -DCIMG_COMPILING -Dcimg_use_rng -Dcimg_use_r -Dcimg_use_fftw3_singlethread -Dcimg_verbosity=1 -Dcimg_date='""' -Dcimg_time='""' -I'/usr/local/lib/R/site-library/Rcpp/include'    -fopenmp -fpic  -g -O2 -ffile-prefix-map=/build/r-base-14Q6vq/r-base-4.3.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c morphology.cpp -o morphology.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -Dcimg_use_fftw3 -I/usr/local/include -I/usr/include/x86_64-linux-gnu -Dcimg_use_tiff -I../inst/include -DCIMG_COMPILING -Dcimg_use_rng -Dcimg_use_r -Dcimg_use_fftw3_singlethread -Dcimg_verbosity=1 -Dcimg_date='""' -Dcimg_time='""' -I'/usr/local/lib/R/site-library/Rcpp/include'    -fopenmp -fpic  -g -O2 -ffile-prefix-map=/build/r-base-14Q6vq/r-base-4.3.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c reductions.cpp -o reductions.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -Dcimg_use_fftw3 -I/usr/local/include -I/usr/include/x86_64-linux-gnu -Dcimg_use_tiff -I../inst/include -DCIMG_COMPILING -Dcimg_use_rng -Dcimg_use_r -Dcimg_use_fftw3_singlethread -Dcimg_verbosity=1 -Dcimg_date='""' -Dcimg_time='""' -I'/usr/local/lib/R/site-library/Rcpp/include'    -fopenmp -fpic  -g -O2 -ffile-prefix-map=/build/r-base-14Q6vq/r-base-4.3.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c transformations.cpp -o transformations.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -Dcimg_use_fftw3 -I/usr/local/include -I/usr/include/x86_64-linux-gnu -Dcimg_use_tiff -I../inst/include -DCIMG_COMPILING -Dcimg_use_rng -Dcimg_use_r -Dcimg_use_fftw3_singlethread -Dcimg_verbosity=1 -Dcimg_date='""' -Dcimg_time='""' -I'/usr/local/lib/R/site-library/Rcpp/include'    -fopenmp -fpic  -g -O2 -ffile-prefix-map=/build/r-base-14Q6vq/r-base-4.3.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c utils.cpp -o utils.o
In file included from /usr/include/stdio.h:894,
                 from /usr/include/c++/11/cstdio:42,
                 from ../inst/include/CImg.h:73,
                 from ../inst/include/imager.h:12,
                 from utils.cpp:1:
In function ‘int fprintf(FILE*, const char*, ...)’,
    inlined from ‘static double cimg_library::CImg<T>::_cimg_math_parser::mp_vector_print(cimg_library::CImg<T>::_cimg_math_parser&) [with T = double]’ at ../inst/include/CImg.h:29015:25:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:105:24: warning: ‘%s’ directive argument is null [-Wformat-overflow=]
  105 |   return __fprintf_chk (__stream, __USE_FORTIFY_LEVEL - 1, __fmt,
      |          ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  106 |                         __va_arg_pack ());
      |                         ~~~~~~~~~~~~~~~~~
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -Dcimg_use_fftw3 -I/usr/local/include -I/usr/include/x86_64-linux-gnu -Dcimg_use_tiff -I../inst/include -DCIMG_COMPILING -Dcimg_use_rng -Dcimg_use_r -Dcimg_use_fftw3_singlethread -Dcimg_verbosity=1 -Dcimg_date='""' -Dcimg_time='""' -I'/usr/local/lib/R/site-library/Rcpp/include'    -fopenmp -fpic  -g -O2 -ffile-prefix-map=/build/r-base-14Q6vq/r-base-4.3.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c wrappers.cpp -o wrappers.o
g++ -std=gnu++11 -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -flto=auto -Wl,-z,relro -o imager.so RcppExports.o colourspace.o coordinates.o display.o drawing.o filtering.o hough.o imgraphs.o interact.o interpolation.o morphology.o reductions.o transformations.o utils.o wrappers.o -fopenmp -lX11 -Dcimg_use_fftw3 -L/usr/local/lib -lfftw3 -ltiff -L/usr/lib/R/lib -lR
**/usr/bin/ld: /usr/local/lib/libfftw3.a(assert.o): warning: relocation against `stdout@@GLIBC_2.2.5' in read-only section `.text'
/usr/bin/ld: /usr/local/lib/libfftw3.a(assert.o): relocation R_X86_64_PC32 against symbol `stdout@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make: *** [/usr/share/R/share/make/shlib.mk:10: imager.so] Error 1
ERROR: compilation failed for package ‘imager’**
* removing ‘/home/mgirond/R/x86_64-pc-linux-gnu-library/4.3/imager’
Warning in install.packages :
  l'installation du package ‘imager’ a eu un statut de sortie non nul

Les packages source téléchargés sont dans
	‘/tmp/RtmpBM3LLy/downloaded_packages’

**Comment by rtobar** [comment]
@Marc-Girondot you have an fftw library under `/use/local` that you probably compiled yourself? That one is being picked, but it doesn't have a shared library, only a static one, and that fails to link.

You could try removing your custom libfftw installation, or if you really need that particular version then try compiling and installing the shared library version next to (or instead of) the static one.

In principle you'd want the `configure` step to catch this. We could add such a check, time permitting.

**Comment by Marc-Girondot** [comment]
Thanks. It was indeed the reason. I have done a post in my blog about that solution.
Thanks a lot
https://www.blogger.com/blog/post/edit/2061052160425746363/789570286751995544
