### ISSUE TITLE
Interactively grabbing multiple points from an image

### ISSUE THREAD

**Issue by aravind-j** [asgr/imager#2]
Is it possible to have an equivalent of `graphics::locator` in `imager` to grab coordinates of multiple points?

```
plot(boats)
locator(n = 4)
```

It is possible with `grabPoint`, but it selects only one point at a time. For multiple points, the image needs to be opened and closed multiple times.

```
grabPoint(boats)
```

This will be useful for large images where `imager::display` is faster than `plot`.

**Comment by aravind-j** [comment]
This issue has already been raised in the archived version of `imager` by @dahtah. 

https://github.com/dahtah/imager/issues/160

**Comment by asgr** [comment]
This is a pretty bespoke use case, so I'd suggest as a first option you try implementing something and submit a pull request. As new maintainers we are much more focussed on fixing bugs for now.
