### ISSUE TITLE
checking whether package ‘imager’ can be installed ... WARNING Found the following significant warnings:   ../inst/include/CImg.h:29015:48: warning: ‘%s’ directive argument is null [-Wformat-overflow=]   ../inst/include/CImg.h:58256:45: warning: ‘%s’ directive argument is null [-Wformat-truncation=]

### ISSUE THREAD

**Issue by billbillbilly** [asgr/imager#20]
Hello,

I am using the package ‘imager’ for my package that came across some issues in the installation related to ‘imager’.

There are some warnings found during the installation of the package ‘imager’:

using R Under development (unstable) (2024-05-07 r86527)
using platform: x86_64-pc-linux-gnu
R was compiled by
    gcc-13 (Debian 13.2.0-24) 13.2.0
    GNU Fortran (Debian 13.2.0-24) 13.2.0
running under: Debian GNU/Linux trixie/sid
using session charset: UTF-8
checking for file ‘imager/DESCRIPTION’ ... OK
checking extension type ... Package
this is package ‘imager’ version ‘1.0.1’
package encoding: UTF-8
checking package namespace information ... OK
checking package dependencies ... OK
checking if this is a source package ... OK
checking if there is a namespace ... OK
checking for executable files ... OK
checking for hidden files and directories ... OK
checking for portable file names ... OK
checking for sufficient/correct file permissions ... OK
checking whether package ‘imager’ can be installed ... WARNING
Found the following significant warnings:
  ../inst/include/CImg.h:29015:48: warning: ‘%s’ directive argument is null [-Wformat-overflow=]
  ../inst/include/CImg.h:58256:45: warning: ‘%s’ directive argument is null [-Wformat-truncation=]

using R Under development (unstable) (2024-05-07 r86527)
using platform: x86_64-pc-linux-gnu
R was compiled by
    gcc-14 (GCC) 14.1.0
    GNU Fortran (GCC) 14.1.0
running under: Fedora Linux 36 (Workstation Edition)
using session charset: UTF-8
using option ‘--no-stop-on-test-error’
checking for file ‘imager/DESCRIPTION’ ... OK
checking extension type ... Package
this is package ‘imager’ version ‘1.0.1’
package encoding: UTF-8
checking package namespace information ... OK
checking package dependencies ... OK
checking if this is a source package ... OK
checking if there is a namespace ... OK
checking for executable files ... OK
checking for hidden files and directories ... OK
checking for portable file names ... OK
checking for sufficient/correct file permissions ... OK
checking whether package ‘imager’ can be installed ... [24m/19m] WARNING
Found the following significant warnings:
  ../inst/include/CImg.h:29015:48: warning: '%s' directive argument is null [-Wformat-overflow=]
  ../inst/include/CImg.h:29246:55: warning: '%d' directive output may be truncated writing between 1 and 10 bytes into a region of size 6 [-Wformat-truncation=]
  ../inst/include/CImg.h:29245:69: warning: '%d' directive output may be truncated writing between 1 and 10 bytes into a region of size 6 [-Wformat-truncation=]

using R version 4.3.3 (2024-02-29 ucrt)
using platform: x86_64-w64-mingw32 (64-bit)
R was compiled by
    gcc.exe (GCC) 12.3.0
    GNU Fortran (GCC) 12.3.0
running under: Windows Server 2022 x64 (build 20348)
using session charset: UTF-8
checking for file 'imager/DESCRIPTION' ... OK
checking extension type ... Package
this is package 'imager' version '1.0.1'
package encoding: UTF-8
checking package namespace information ... OK
checking package dependencies ... OK
checking if this is a source package ... OK
checking if there is a namespace ... OK
checking for hidden files and directories ... OK
checking for portable file names ... OK
checking whether package 'imager' can be installed ... WARNING
Found the following significant warnings:
  D:/rtools43/usr/lib/mxe/usr/x86_64-w64-mingw32.static.posix/include/winnt.h:8404:37: warning: ISO C++ forbids flexible array member 'Elements' [-Wpedantic]
  D:/rtools43/usr/lib/mxe/usr/x86_64-w64-mingw32.static.posix/include/winnt.h:8667:22: warning: ISO C++ forbids flexible array member 'pEventLogRecords' [-Wpedantic]
  D:/rtools43/usr/lib/mxe/usr/x86_64-w64-mingw32.static.posix/include/winnt.h:8673:13: warning: ISO C++ forbids flexible array member 'ulOffsets' [-Wpedantic]
  D:/rtools43/usr/lib/mxe/usr/x86_64-w64-mingw32.static.posix/include/rpcndr.h:447:19: warning: ISO C++ forbids flexible array member 'Format' [-Wpedantic]
  D:/rtools43/usr/lib/mxe/usr/x86_64-w64-mingw32.static.posix/include/oaidl.h:548:37: warning: ISO C++ prohibits anonymous structs [-Wpedantic]
  D:/rtools43/usr/lib/mxe/usr/x86_64-w64-mingw32.static.posix/include/oaidl.h:499:29: warning: ISO C++ prohibits anonymous structs [-Wpedantic]
See the [install log](https://www.r-project.org/nosvn/R.check/r-oldrel-windows-x86_64/imager-00install.html) for details.

Can these issues be fixed? Thank you.

All the best
Bill

**Comment by rtobar** [comment]
@billbillbilly we're aware of the issues and will try to fix them to avoid having the package removed from CRAN.

**Comment by rtobar** [comment]
@billbillbilly issues are gone in the latest CRAN version, checks are already showing no warnings with 1.0.2: https://cran.r-project.org/web/checks/check_results_imager.html
