### ISSUE TITLE
Question: Can I update the vignette, there seems to be a fair bit missing

### ISSUE THREAD

**Issue by EngrStudent** [asgr/imager#22]
Question: Can I update the vignette, there seems to be a fair bit missing

The bottom of the vignette looks like this:
![image](https://github.com/asgr/imager/assets/10841261/c6509afe-df1a-4118-937c-1947f4c6d139)

I think that is a placeholder.  

I like to ask permission before messing with someone else's stuff.  Would it be okay if I tried to fill in some of the missing stuff?

**Comment by asgr** [comment]
This vignette just points to these functions as having associated help files with their own examples, which they do (check ?imblur etc). The idea behind this vignette isn't to recapitulate the entire help documentation of imager, but just get you started. Note I didn't write this vignette- that was the original author of imager.
