### ISSUE TITLE
Package-development reliant on imager: R-CMD Check via GH Actions fails on ubuntu runners.

### ISSUE THREAD

**Issue by Claudius-Appel** [asgr/imager#24]
Hello,

I was performing some bug-fixing on my end on a package ([Claudius-Appel/duflor.gui](Claudius-Appel/duflor.gui)) depending on imager.

I check for errors using a slightly altered[^2] version of the standard `R CMD Check`-Workflow for Github actions, see [R-CMD-check.yaml](https://github.com/Claudius-Appel/duflor.gui/blob/dev_3/.github/workflows/R-CMD-check.yaml).

The previous run `#83` - and most others beforehand - succeeded. Neither the renv-lockfile, nor the package requirements in the DESCRIPTION were updated since.

However, take a look at [this workflow execution](https://github.com/Claudius-Appel/duflor.gui/actions/runs/11308654438). In particular, in any of the ubuntu-runners, inspect step `Run r-lib/actions/setup-r-dependencies@v2`, and search for `Building imager 1.0.2`. For reasons unknown to me, this fails now, citing a missing x11 library for using the display-dependencies of CImg. I assume this error is raised because my code imports `imager::display()`? But then again calls to `imager::display()` were not introduced in this update; but have been part of the package for quite a while - and succeeded tests till now.

I am not sure what to make of this, or what steps should be taken to resolve it. The configuration is identical on my end between https://github.com/Claudius-Appel/duflor.gui/commit/d851c1ad8a8e47fb74fbd8a8a4b125f54135d965 and https://github.com/Claudius-Appel/duflor.gui/commit/d539c164e89b2b745941beb92390e0bf99f693ee, and the changes performed between the last successfull run on branch [dev](https://github.com/Claudius-Appel/duflor.gui/tree/dev) and this merge into [dev_3](https://github.com/Claudius-Appel/duflor.gui/tree/dev_3)[^1]. This leaves me coming here; because to my understanding I don't see what exactly should be responsible for this sudden failure. 

I develop on Win11, and checks pass locally and on the GH runner for windows.

---

Do you have any insight or ideas as to how to resolve this issue? 

Thank you.
Sincerely,
~CA

[^1]: `dev_3` mirrors modifications to `dev`, except that dev_3 has a couple private modifications I need personally but don't consider integral to the actual project. They are unrelated to imager.
[^2]: altered in that additional branches can trigger the workflow, and macOS-checks are removed as not needed. Derived from https://github.com/r-lib/actions/blob/v2-branch/examples/README.md#standard-ci-workflow

**Comment by rtobar** [comment]
@Claudius-Appel we haven't changed imager in the time period where your pipelines started failing, let alone release a new version, so this is clearly a problem with your environment.

I'm not greatly familiar with how the `setup-r` action works, but the line:

```
  ℹ Executing `sudo sh -c apt-get -y install make zlib1g-dev libglpk-dev libxml2-dev libfftw3-dev libtiff-dev libjpeg-dev pandoc libpng-dev libicu-dev libcurl4-openssl-dev libssl-dev`
```

would be missing the `libx11-dev` package. How that list is determined and by whom is unknown to me.

Note also that `ubuntu-latest` is a moving target, and is in the [process of being moved](https://github.com/actions/runner-images/issues/10636) from `ubuntu-22.04` to `ubuntu-24.04`. Most likely the 22.04 base image did come with `libx11-dev` pre-installed while `24.04` doesn't. The patch solution is obviously to pin your runners to `ubuntu-22.04` for the time being.

**Comment by Claudius-Appel** [comment]
> would be missing the libx11-dev package

I don't think this line is indicative of the issue - because the logs for the failing run on `ubuntu-latest (release)`
![grafik](https://github.com/user-attachments/assets/a9659b82-3d86-44ed-889b-560a699e2887)


_and_ for the last successfull run 
![grafik](https://github.com/user-attachments/assets/a6302f38-305e-4a30-8ace-170be358d3dd)


both don't mention the installation of the `libx11-dev`-package.


However, I just re-ran an old test which succeeded before, and now it exhibits the same issue as current runs. This would suggest the issue to lie somewhere upstream in the action itself.

**Comment by rtobar** [comment]
I'm closing this since it's clearly not an issue with imager, and additionally you've already validated that pinning to `ubuntu-22.04` works, as suggested.

**Comment by Claudius-Appel** [comment]
Yup. Thank you for the pointer, I don't think I would have found that this soon.

**Comment by rtobar** [comment]
@Claudius-Appel FYI, a few days ago a different person ran into similar issues. I ended up fixing what needed to be fixed, and thus soon installation under `ubuntu-24.04` should work, see linked issues above.
