### ISSUE TITLE
Problem using load.video() from paths with spaces

### ISSUE THREAD

**Issue by mmejia23** [asgr/imager#7]
I was having troubles loading .avi files with load.video(), but just with some files and not others, giving me this error:
> Error in tryCatchList(expr, classes, parentenv, handlers) : 
>  No output was generated

Found this [unresolved old issue in the previous repository](https://github.com/dahtah/imager/issues/92), with the same error. Not sure if it was caused by the same reason, but in my case, the problem was that the path to the video file had spaces in it. So, it resolved when I changed spaces into underscores (_), and I could recreate the error with other paths.

I was using imager 0.42 first, but then I installed the 0.45.2 and still throws the same error on that condition.

**Comment by asgr** [comment]
I don't think that is necessarily an imager bug in which case- closing issue.
