### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by DM0815** [asgr/imager#8]
Excuse me, when I install package by devtools::install_github("asgr/imager"), before this I have conducted command'sudo apt install libfftw3-dev libtiff-dev libxml2-dev libicu-dev libgmp-dev libpng-dev libglpk-dev' ,but after devtools, it reminds that as figures described
<img width="1180" alt="1705151549928" src="https://github.com/asgr/imager/assets/89619779/426c902f-84c0-45b7-ba42-7e17fd9d3ec7">
 How do I solve it?  My linux is Ubuntu 22.04.2 LTS

**Comment by rtobar** [comment]
@DM0815 could you please provide the full log of the build, and the command you're using to do it? And not as an image, but as plain text please, otherwise it's difficult to read.

Have you also tried installing from CRAN instead of trying from GitHub? I'm inclined to think there's something wrong with your installation.

I also see you're using Anaconda, in which case you could try using a different gcc version and see if that changes things.

From my standpoint I don't understand what could cause the error. `std::acos` *has* an overload that takes `double` values, so there shouldn't be an error here.

**Comment by DM0815** [comment]
> tried installing from CRAN

Yes,I tried installing from CRAN ,but also failed, and have to install from GitHub,, when installing from CRAN, it reminds that
** using staged installation
checking for pkg-config... /usr/bin/pkg-config
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether x86_64-conda-linux-gnu-c++ -std=gnu++17 accepts -g... yes
checking how to run the C++ preprocessor... x86_64-conda-linux-gnu-c++ -std=gnu++17 -E
checking for X... libraries , headers 
checking for XOpenDisplay in -lX11... yes
X11 library found.
configure: Checking if FFTW3 library is available using pkg-config
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for FFTW... yes
FFTW3 found!
checking whether pkg-config knows about libtiff-4... yes
checking for configurable backends... checking whether --static is needed... no
checking for x86_64-conda-linux-gnu-c++ -std=gnu++17 option to support OpenMP... -fopenmp
configure: creating ./config.status
config.status: creating src/Makevars
** libs
using C++ compiler: ‘x86_64-conda-linux-gnu-c++ (conda-forge gcc 12.1.0-17) 12.1.0’
x86_64-conda-linux-gnu-c++ -std=gnu++17 -I"/home/dm/anaconda3/envs/r4.3/lib/R/include" -DNDEBUG -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/dm/anaconda3/envs/r4.3/include -I/home/dm/anaconda3/envs/r4.3/include -Wl,-rpath-link,/home/dm/anaconda3/envs/r4.3/lib  -Dcimg_use_fftw3  -I/usr/include/x86_64-linux-gnu -Dcimg_use_tiff -I../inst/include -DCIMG_COMPILING -Dcimg_use_rng -Dcimg_use_r -Dcimg_use_fftw3_singlethread -Dcimg_verbosity=1 -Dcimg_date='""' -Dcimg_time='""' -I'/home/dm/anaconda3/envs/r4.3/lib/R/library/Rcpp/include' -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/dm/anaconda3/envs/r4.3/include -I/home/dm/anaconda3/envs/r4.3/include -Wl,-rpath-link,/home/dm/anaconda3/envs/r4.3/lib   -fopenmp -fpic  -fvisibility-inlines-hidden  -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/dm/anaconda3/envs/r4.3/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base-split_1689933267587/work=/usr/local/src/conda/r-base-4.3.1 -fdebug-prefix-map=/home/dm/anaconda3/envs/r4.3=/usr/local/src/conda-prefix  -c RcppExports.cpp -o RcppExports.o
In file included from /home/dm/anaconda3/envs/r4.3/x86_64-conda-linux-gnu/sysroot/usr/include/features.h:361,
                 from /home/dm/anaconda3/envs/r4.3/x86_64-conda-linux-gnu/include/c++/12.1.0/x86_64-conda-linux-gnu/bits/os_defines.h:39,
                 from /home/dm/anaconda3/envs/r4.3/x86_64-conda-linux-gnu/include/c++/12.1.0/x86_64-conda-linux-gnu/bits/c++config.h:655,
                 from /home/dm/anaconda3/envs/r4.3/x86_64-conda-linux-gnu/include/c++/12.1.0/cstdlib:41,
                 from /home/dm/anaconda3/envs/r4.3/lib/R/include/R.h:39,
                 from ../inst/include/imager.h:12,
                 from RcppExports.cpp:4:
/usr/include/x86_64-linux-gnu/sys/cdefs.h:146:55: error: missing binary operator before token "("
  146 | #if __USE_FORTIFY_LEVEL == 3 && (__glibc_clang_prereq (9, 0)                  \
      |                                                       ^
/usr/include/x86_64-linux-gnu/sys/cdefs.h:634:49: error: missing binary operator before token "("
  634 | #if __GNUC_PREREQ (4,8) || __glibc_clang_prereq (3,5)
      |                                                 ^
In file included from /home/dm/anaconda3/envs/r4.3/x86_64-conda-linux-gnu/sysroot/usr/include/stdio.h:93,
                 from /home/dm/anaconda3/envs/r4.3/x86_64-conda-linux-gnu/include/c++/12.1.0/cstdio:42,
                 from /home/dm/anaconda3/envs/r4.3/lib/R/include/R.h:40:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:233:17: error: missing binary operator before token "("
  233 | #if __GLIBC_USE (DEPRECATED_GETS)
      |                 ^
In file included from /home/dm/anaconda3/envs/r4.3/x86_64-conda-linux-gnu/sysroot/usr/include/math.h:47,
                 from /home/dm/anaconda3/envs/r4.3/x86_64-conda-linux-gnu/include/c++/12.1.0/cmath:45,
                 from /home/dm/anaconda3/envs/r4.3/lib/R/include/R.h:41:
/usr/include/x86_64-linux-gnu/bits/mathdef.h:19:3: error: #error "Never use <bits/mathdef.h> directly; include <complex.h> instead"
   19 | # error "Never use <bits/mathdef.h> directly; include <complex.h> instead"
      |   ^~~~~
In file included from /home/dm/anaconda3/envs/r4.3/x86_64-conda-linux-gnu/sysroot/usr/include/math.h:71:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:112:17: error: missing binary operator before token "("
  112 | #if __GLIBC_USE (IEC_60559_FUNCS_EXT_C2X)
      |                 ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:267:18: error: missing binary operator before token "("
  267 | # if __GLIBC_USE (IEC_60559_BFP_EXT_C2X) || __MATH_DECLARING_FLOATN
      |                  ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:286:17: error: missing binary operator before token "("
  286 | #if __GLIBC_USE (IEC_60559_BFP_EXT_C2X) || __MATH_DECLARING_FLOATN
      |                 ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:331:68: error: missing binary operator before token "("
  331 | # if !__MATH_DECLARING_FLOATN || defined __USE_GNU || !__GLIBC_USE (ISOC2X)
      |                                                                    ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:343:17: error: missing binary operator before token "("
  343 | #if __GLIBC_USE (IEC_60559_BFP_EXT_C2X) || __MATH_DECLARING_FLOATN
      |                 ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:373:18: error: missing binary operator before token "("
  373 | #if (__GLIBC_USE (IEC_60559_BFP_EXT)                            \
      |                  ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:383:17: error: missing binary operator before token "("
  383 | #if __GLIBC_USE (ISOC2X)
      |                 ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:409:17: error: missing binary operator before token "("
  409 | #if __GLIBC_USE (IEC_60559_EXT) || __MATH_DECLARING_FLOATN
      |                 ^
In file included from /home/dm/anaconda3/envs/r4.3/x86_64-conda-linux-gnu/sysroot/usr/include/math.h:94:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:112:17: error: missing binary operator before token "("
  112 | #if __GLIBC_USE (IEC_60559_FUNCS_EXT_C2X)
      |                 ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:267:18: error: missing binary operator before token "("
  267 | # if __GLIBC_USE (IEC_60559_BFP_EXT_C2X) || __MATH_DECLARING_FLOATN
      |                  ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:286:17: error: missing binary operator before token "("
  286 | #if __GLIBC_USE (IEC_60559_BFP_EXT_C2X) || __MATH_DECLARING_FLOATN
      |                 ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:331:68: error: missing binary operator before token "("
  331 | # if !__MATH_DECLARING_FLOATN || defined __USE_GNU || !__GLIBC_USE (ISOC2X)
      |                                                                    ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:343:17: error: missing binary operator before token "("
  343 | #if __GLIBC_USE (IEC_60559_BFP_EXT_C2X) || __MATH_DECLARING_FLOATN
      |                 ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:373:18: error: missing binary operator before token "("
  373 | #if (__GLIBC_USE (IEC_60559_BFP_EXT)                            \
      |                  ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:383:17: error: missing binary operator before token "("
  383 | #if __GLIBC_USE (ISOC2X)
      |                 ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:409:17: error: missing binary operator before token "("
  409 | #if __GLIBC_USE (IEC_60559_EXT) || __MATH_DECLARING_FLOATN
      |                 ^
In file included from /home/dm/anaconda3/envs/r4.3/x86_64-conda-linux-gnu/sysroot/usr/include/math.h:141:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:112:17: error: missing binary operator before token "("
  112 | #if __GLIBC_USE (IEC_60559_FUNCS_EXT_C2X)
      |                 ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:267:18: error: missing binary operator before token "("
  267 | # if __GLIBC_USE (IEC_60559_BFP_EXT_C2X) || __MATH_DECLARING_FLOATN
      |                  ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:286:17: error: missing binary operator before token "("
  286 | #if __GLIBC_USE (IEC_60559_BFP_EXT_C2X) || __MATH_DECLARING_FLOATN
      |                 ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:331:68: error: missing binary operator before token "("
  331 | # if !__MATH_DECLARING_FLOATN || defined __USE_GNU || !__GLIBC_USE (ISOC2X)
      |                                                                    ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:343:17: error: missing binary operator before token "("
  343 | #if __GLIBC_USE (IEC_60559_BFP_EXT_C2X) || __MATH_DECLARING_FLOATN
      |                 ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:373:18: error: missing binary operator before token "("
  373 | #if (__GLIBC_USE (IEC_60559_BFP_EXT)                            \
      |                  ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:383:17: error: missing binary operator before token "("
  383 | #if __GLIBC_USE (ISOC2X)
      |                 ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:409:17: error: missing binary operator before token "("
  409 | #if __GLIBC_USE (IEC_60559_EXT) || __MATH_DECLARING_FLOATN
      |                 ^
In file included from ../inst/include/imager.h:27:
../inst/include/CImg.h:523:10: fatal error: fftw3.h: No such file or directory
  523 | #include "fftw3.h"
      |          ^~~~~~~~~
compilation terminated.
make: *** [/home/dm/anaconda3/envs/r4.3/lib/R/etc/Makeconf:200：RcppExports.o] 错误 1
ERROR: compilation failed for package ‘imager’
* removing ‘/home/dm/anaconda3/envs/r4.3/lib/R/library/imager’

**Comment by DM0815** [comment]
Now It reminds that fatal error: fftw3.h: No such file or directory. I find it's strange because I have conducted sudo apt install libfftw3-dev.  Actually, I reinstall libfftw3, after removing it,it reminds the faults as figures described.

**Comment by rtobar** [comment]
I think you're getting into errors because you're using Anaconda and a compiler within Anaconda, but installed fftw and the other libraries with your system package manager, which is added include paths from your system rather than from Anaconda.

I'd recommend removing those packages you installed with `apt` and installing them with `conda` instead in your Anaconda installation, then trying again. All in all, doesn't look like an issue with `imager` so far.

**Comment by DM0815** [comment]
> I think you're getting into errors because you're using Anaconda and a compiler within Anaconda, but installed fftw and the other libraries with your system package manager, which is added include paths from your system rather than from Anaconda.
> 
> I'd recommend removing those packages you installed with `apt` and installing them with `conda` instead in your Anaconda installation, then trying again. All in all, doesn't look like an issue with `imager` so far.

Got it. Thanks, I will try it

**Comment by DM0815** [comment]
> I think you're getting into errors because you're using Anaconda and a compiler within Anaconda, but installed fftw and the other libraries with your system package manager, which is added include paths from your system rather than from Anaconda.
> 
> I'd recommend removing those packages you installed with `apt` and installing them with `conda` instead in your Anaconda installation, then trying again. All in all, doesn't look like an issue with `imager` so far.

I'm soory to bother you. But I cannot install fftw3 by conda install, there are some problems. Do you have some other suggestions about installing imager? Can you give me some hints.  such as r2u, but r2u didnot include imager package.
